### ISSUE TITLE
Unable to get work PHPMD ...

### ISSUE THREAD

**Issue by scramatte** [bruli/php-git-hooks#125]
PHPMD neither works ...

```
Pre-Commit tool
Checking composer files...........................0K
Checking json files...............................0K
Running PHPLINT...................................0K
Checking code style with PHPCS....................0K
Checking code mess with PHPMD.....................
Fail

Cannot find specified rule-set "./PmdRules.xml".
```

**Comment by alexgivi** [comment]
https://github.com/bruli/php-git-hooks/blob/master/PmdRules.xml
try to copy this file to your project dir...

**Comment by alexssandrog** [comment]
Hi, here is occurring the message below

`Checking code mess with PHPMD.....................PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in /home/alex/projects/truckpag/gestao-api/vendor/bruli/php-git-hooks/src/PhpGitHooks/Module/PhpMd/Infrastructure/Tool/PhpMdToolProcessor.php on line 49 and defined in /home/alex/projects/truckpag/gestao-api/vendor/symfony/process/Process.php:140
Stack trace:
#0 /home/alex/projects/truckpag/gestao-api/vendor/bruli/php-git-hooks/src/PhpGitHooks/Module/PhpMd/Infrastructure/Tool/PhpMdToolProcessor.php(49): Symfony\Component\Process\Process->__construct('php vendor/bin/...')
#1 /home/alex/projects/truckpag/gestao-api/vendor/bruli/php-git-hooks/src/PhpGitHooks/Module/PhpMd/Infrastructure/Tool/PhpMdToolProcessor.php(34): PhpGitHooks\Module\PhpMd\Infrastructure\Tool\PhpMdToolProcessor->execute('index.php', NULL)
#2 /home/alex/projects/truckpag/gestao-api/vendor/bruli/php-git-hooks/src/PhpGitHooks/Module/PhpMd/Contract/Command/PhpMdToolHandler.php(51): PhpGitHooks\Module\PhpMd\Infr in /home/alex/projects/truckpag/gestao-api/vendor/symfony/process/Process.php on line 140`
